### ISSUE TITLE
Preferences Editor package, KeyError: 'SQL', when trying to edit any settings

### ISSUE THREAD

**Issue by evandrocoan** [evandrocoan/SublimeTextStudio#25]
### Preferences Editor package, KeyError: 'SQL', when trying to edit any settings

```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "Preferences Editor in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Preferences Editor.sublime-package", line 876, in run
KeyError: 'SQL'
```

Opened a issue on: 

1. https://bitbucket.org/klorenz/sublimepreferenceseditor/issues/10

Seems related to: 

1. https://bitbucket.org/klorenz/sublimepreferenceseditor/issues/8/getting-weird-error-when-trying-to-open

> I get this error whenever I try to invoke the "current syntax" item from the command palette when a syntax specific preference file does not yet exist.
If I choose to open the Syntax specific preference, and save the empty file, and run the "Current Syntax" item again, I can use the plugin without issue.

**Comment by evandrocoan** [comment]
Fixed on: 

1. Issue: https://github.com/evandrocoan/SublimePreferencesEditor/issues/1
1. Commit: https://github.com/evandrocoan/SublimePreferencesEditor/commit/fba6905b48e003fd45731d6f20a1a10877c1b8ac
