### ISSUE TITLE
[BufferScroll] TypeError: get() missing 1 required positional argument: 'view'

### ISSUE THREAD

**Issue by evandrocoan** [evandrocoan/SublimeTextStudio#49]
There is a error which could pop some times directly to this line.

```
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\SublimeText\sublime_plugin.py", line 488, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "D:\SublimeText\Data\Packages\BufferScroll\BufferScroll.py", line 304, in on_modified
    if not view.settings().get('is_widget') and not view.is_scratch() and len(view.sel()) == 1 and Pref.get('typewriter_scrolling', view):
TypeError: get() missing 1 required positional argument: 'view'
```

How to reproduce this?

**Comment by evandrocoan** [comment]
There is some time I do not see this anymore, perhaps it is fixed?
